# Generated by Django 5.1.3 on 2024-12-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0002_person_pseudonim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='pseudonim',
            field=models.CharField(default='', max_length=80),
        ),
    ]
